#!/usr/bin/env python3
"""Annotation-only QA generation for JIGSAWS (Suturing, Knot_Tying, Needle_Passing), templates A-D.

This runner never reads video or extracts frames. Prompts are built solely from
real JIGSAWS annotations (meta_file GRS scores, skill level, gesture
transcriptions), and the model generates question/answer/rationale itself.
There are no canned or label-templated answers anywhere in this script; the
only label-derived values passed to the model are the annotations themselves.

Two granularities are supported:
- gesture (default): one QA object per gesture span, timestamp_or_frame is a
  frame range. Every gesture in a trial shares the same GRS scores, so this
  produces many near-duplicate coaching questions per trial.
- video: one QA object per whole trial, timestamp_or_frame is a timestamp
  range (converted from the annotated gesture spans' frame extent at
  JIGSAWS's 30 fps capture rate, per Gao et al. 2014), grounded only in that
  trial's GRS scores.

Every output record carries provenance: backend ("real" or "mock"),
real_model_inference, model_id, the exact prompt, and the raw model output.
Mock records are additionally watermarked and written with
validation_status "valid_mock" so they can never be confused with real data.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


GRS_NAMES = [
    "respect_for_tissue",
    "suture_needle_handling",
    "time_and_motion",
    "flow_of_operation",
    "overall_performance",
    "quality_of_final_product",
]

# Plain-language labels for D2/D3/D4's "three feedback points": these are
# named directly in the question text (not left as an unexplained "these
# three feedback points"), so a reader needs no hidden context to understand
# or attempt to answer the question.
GRS_PLAIN_LABELS = {
    "respect_for_tissue": "tissue handling",
    "suture_needle_handling": "instrument/needle handling",
    "time_and_motion": "economy of motion",
    "flow_of_operation": "flow of operation",
    "overall_performance": "overall procedural performance",
    "quality_of_final_product": "quality of the final product",
}


def three_lowest_feedback_points(grs_subscores: dict[str, int]) -> list[str]:
    """The three lowest-rated GRS subscores, as plain-language labels.

    Ties are broken by GRS_NAMES order, so this is fully deterministic and
    reproducible independent of anything the model does -- required so the
    exact-question-wording validator can compute its own expected answer.
    """
    ordered = sorted(GRS_NAMES, key=lambda name: (grs_subscores[name], GRS_NAMES.index(name)))
    return [GRS_PLAIN_LABELS[name] for name in ordered[:3]]


def format_feedback_points(points: list[str]) -> str:
    if len(points) == 1:
        return points[0]
    if len(points) == 2:
        return f"{points[0]} and {points[1]}"
    return f"{', '.join(points[:-1])}, and {points[-1]}"


# Each record in a run is generated by an independent model call with no
# memory of what it wrote for other records -- a shared system prompt alone
# cannot make it aware it already used a given opening construction twice.
# Threading recent openers into each subsequent prompt gives it that
# cross-record awareness directly, per template_id (D2 answers shouldn't be
# compared against D5 answers, for example).
RECENT_OPENERS_TO_SHOW = 5


def first_sentence(text: str, max_words: int = 25) -> str:
    match = re.match(r"(.+?[.!?])(\s|$)", text)
    sentence = match.group(1) if match else text
    words = sentence.split()
    if len(words) > max_words:
        sentence = " ".join(words[:max_words]) + "..."
    return sentence


TASK_LABELS = {
    "Suturing": "Suturing",
    "Knot_Tying": "Knot Tying",
    "Needle_Passing": "Needle Passing",
}

# JIGSAWS self-proclaimed experience levels (Gao et al., 2014). Glossed in the
# prompt because a bare "N"/"I"/"E" is opaque -- a model left to guess has been
# observed calling level I "novice" when I means intermediate.
SKILL_LEVELS = {
    "N": "novice, <10 hours robotic surgical practice",
    "I": "intermediate, 10-100 hours robotic surgical practice",
    "E": "expert, >100 hours robotic surgical practice",
}

# JIGSAWS videos are captured at 30 fps (Gao et al., 2014). Used only to
# convert annotated frame spans into timestamps for --granularity video;
# never used to infer anything visual.
JIGSAWS_FPS = 30


def frame_to_timestamp(frame: int, fps: int = JIGSAWS_FPS) -> str:
    total_seconds = round(frame / fps)
    minutes, seconds = divmod(total_seconds, 60)
    return f"{minutes}:{seconds:02d}"

# Standard JIGSAWS gesture vocabulary (Gao et al., 2014).
GESTURE_DEFINITIONS = {
    "G1": "Reaching for needle with right hand",
    "G2": "Positioning needle",
    "G3": "Pushing needle through tissue",
    "G4": "Transferring needle from left to right",
    "G5": "Moving to center with needle in grip",
    "G6": "Pulling suture with left hand",
    "G7": "Pulling suture with right hand",
    "G8": "Orienting needle",
    "G9": "Using right hand to help tighten suture",
    "G10": "Loosening more suture",
    "G11": "Dropping suture at end and moving to end points",
    "G12": "Reaching for needle with left hand",
    "G13": "Making C loop around right hand",
    "G14": "Reaching for suture with right hand",
    "G15": "Pulling suture with both hands",
}

# Templates that JIGSAWS annotations (skill level, GRS scores, gesture spans)
# can actually support without visual input. Everything else is refused with a
# reason instead of being generated from thin air.
SUPPORTED_TEMPLATES = {
    "C1": "respect_for_tissue GRS subscore",
    "C2": "suture_needle_handling GRS subscore",
    "C3": "time_and_motion GRS subscore",
    "C6": "flow_of_operation GRS subscore",
    "C7": "skill_level and grs_total",
    "D1": "GRS subscores and gesture span",
    "D2": "GRS subscores rank the three feedback points",
    "D3": "GRS subscores rank the three feedback points",
    "D4": "weakest GRS subscore selects the drill target",
    "D5": "strongest GRS subscore supports reinforcement",
}
UNSUPPORTED_TEMPLATES = {
    # Type A targets Endoscapes2023 (secondary PitVQA), not JIGSAWS.
    "A1": "Type A is not a JIGSAWS type; JIGSAWS also has no anatomy or instrument labels",
    "A2": "Type A is not a JIGSAWS type; phase/step identification needs MultiBypass140-style labels",
    "A3": "Type A is not a JIGSAWS type; A3 is a two-clip comparison this one-clip-per-item pipeline cannot build",
    "A4": "Type A is not a JIGSAWS type; JIGSAWS has no visual-field-quality labels",
    "B1": "JIGSAWS has no safety/error labels",
    "B2": "JIGSAWS has no safety/error labels",
    "B3": "JIGSAWS has no safety/error labels",
    "B4": "JIGSAWS has no near-miss labels",
    "B5": "JIGSAWS has no safety/error labels",
    "C4": "JIGSAWS has no bimanual-coordination label",
    "C5": "JIGSAWS has no targeting/accuracy label",
}

MOCK_WATERMARK = "[MOCK OUTPUT - NOT MODEL-GENERATED - SMOKE TEST ONLY]"


def log(message: str) -> None:
    print(message, flush=True)


def extract_system_prompt(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"```text\n(.*?)\n```", text, flags=re.DOTALL)
    prompt = match.group(1).strip() if match else text.strip()

    def include_file(include_match: re.Match[str]) -> str:
        include_path = (path.parent / include_match.group(1).strip()).resolve()
        return include_path.read_text(encoding="utf-8").strip()

    return re.sub(r"\{\{include:\s*([^}]+?)\s*\}\}", include_file, prompt).strip()


UNSPECIFIED_TEMPLATE = "not yet specified"
REQUIRES_VISION_MARKER = "status: requires-vision"


def load_question_templates(path: Path) -> dict[str, str]:
    """Parse canonical A-D question wording from the template markdown.

    Templates whose body begins "not yet specified" have no agreed wording and
    are omitted, so asking for one fails loudly rather than silently sending
    the placeholder prose to the model as a question.
    """
    text = path.read_text(encoding="utf-8")
    templates: dict[str, str] = {}
    for match in re.finditer(
        r"## Template ([A-D]\d)[^\n]*\n+```text\n(.*?)\n```", text, flags=re.DOTALL
    ):
        templates[match.group(1)] = match.group(2).strip()
    if not templates:
        # Fall back to fence-less section bodies.
        for match in re.finditer(
            r"## Template ([A-D]\d)[^\n]*\n+(.*?)(?=\n## |\Z)", text, flags=re.DOTALL
        ):
            templates[match.group(1)] = match.group(2).strip()
    usable: dict[str, str] = {}
    for tid, body in templates.items():
        if body.lower().startswith(UNSPECIFIED_TEMPLATE):
            continue
        # "> status: requires-vision" marks canonical wording that asks the
        # model to describe what it sees. That wording is recorded for
        # reference but cannot be used annotation-only, so it is excluded by
        # declaration rather than by accident of formatting.
        if REQUIRES_VISION_MARKER in body.lower():
            continue
        # Drop "> ..." commentary; it documents the template for humans and is
        # not part of the question.
        lines = [ln for ln in body.splitlines() if not ln.lstrip().startswith(">")]
        questions = [ln.strip() for ln in lines if ln.strip()]
        # A template listing several alternative questions cannot be sent as
        # one; skip it so a runner asking for it fails loudly rather than
        # joining them together.
        if len(questions) != 1:
            continue
        usable[tid] = questions[0]
    return usable


def load_d_templates(path: Path) -> dict[str, str]:
    """A-D templates, with D1-D5 required (this runner cannot work without them)."""
    templates = load_question_templates(path)
    missing = {"D1", "D2", "D3", "D4", "D5"} - set(templates)
    if missing:
        raise ValueError(f"Missing D templates in {path}: {sorted(missing)}")
    return templates


def read_meta(dataset_root: Path, trial_id: str, task: str) -> dict[str, Any]:
    meta_path = dataset_root / f"meta_file_{task}.txt"
    for line in meta_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        parts = line.split()
        if parts[0] != trial_id:
            continue
        scores = {name: int(value) for name, value in zip(GRS_NAMES, parts[3:9])}
        return {
            "trial_id": parts[0],
            "skill_level": parts[1],
            "grs_total": int(parts[2]),
            "grs_subscores": scores,
            "source_file": str(meta_path),
        }
    raise KeyError(f"Trial {trial_id} not found in {meta_path}")


def read_gesture_spans(dataset_root: Path, trial_id: str) -> list[dict[str, Any]]:
    path = dataset_root / "transcriptions" / f"{trial_id}.txt"
    spans: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        start, end, gesture_id = line.split()[:3]
        spans.append(
            {
                "gesture_id": gesture_id,
                "start_frame": int(start),
                "end_frame": int(end),
                "source_file": str(path),
            }
        )
    if not spans:
        raise ValueError(f"No gesture spans in {path}")
    return spans


def feedback_points_label(
    template_id: str, d_templates: dict[str, str], grs_subscores: dict[str, int]
) -> str | None:
    """The formatted "[three feedback points]" substitution for D2/D3/D4, or
    None for templates whose wording doesn't reference it (D1, D5)."""
    if template_id not in d_templates:
        return None
    if "[three feedback points]" not in d_templates[template_id]:
        return None
    return format_feedback_points(three_lowest_feedback_points(grs_subscores))


def render_d_question(
    template_id: str, d_templates: dict[str, str], span_label: str, feedback_points: str | None
) -> str:
    question = d_templates[template_id].replace("[a certain video span]", span_label)
    if feedback_points is not None:
        question = question.replace("[three feedback points]", feedback_points)
    return question


def recent_openers_block(recent_openers: list[str] | None) -> list[str]:
    if not recent_openers:
        return []
    lines = [
        "",
        "Answer openings already used earlier in this batch -- do not reuse this",
        "construction or a close paraphrase of it; open this answer a genuinely",
        "different way:",
    ]
    lines += [f'- "{opener}"' for opener in recent_openers]
    return lines


def build_user_prompt(
    template_id: str,
    meta: dict[str, Any],
    span: dict[str, Any],
    d_templates: dict[str, str],
    procedure_or_task: str = "Suturing",
    recent_openers: list[str] | None = None,
) -> str:
    frame_label = f"{span['start_frame']}-{span['end_frame']}"
    gesture_definition = GESTURE_DEFINITIONS.get(span["gesture_id"], "unknown gesture")
    feedback_points = feedback_points_label(template_id, d_templates, meta["grs_subscores"])
    lines = [
        "Dataset-specific input (ANNOTATION-ONLY: no frames or images are attached):",
        "- dataset_name: JIGSAWS",
        f"- procedure_or_task: {procedure_or_task}",
        f"- video_id: {meta['trial_id']}",
        f"- clip_id: {meta['trial_id']}_{frame_label}",
        f"- timestamp_or_frame: frames {frame_label}",
        f"- requested_template_ids: {template_id}",
        "- number_of_questions: 1",
        "- available_annotations:",
        f"  - trial_id: {meta['trial_id']}",
        f"  - skill_level: {meta['skill_level']} ({SKILL_LEVELS.get(meta['skill_level'], 'unknown')})",
        f"  - grs_total: {meta['grs_total']}",
        f"  - grs_subscores: {json.dumps(meta['grs_subscores'], sort_keys=True)}",
        f"  - gesture_id: {span['gesture_id']} ({gesture_definition})",
        f"  - gesture_frame_range: {frame_label}",
    ]
    if feedback_points is not None:
        lines.append(f"  - three_feedback_points: {feedback_points}")
    lines += [
        "",
        "Ground the QA pair only in these annotations. Do not describe any visual",
        "content; no visual content was provided.",
    ]
    if template_id in d_templates:
        lines += recent_openers_block(recent_openers)
        question = render_d_question(template_id, d_templates, f"frames {frame_label}", feedback_points)
        lines += ["", "Use this exact question text:", question]
    lines += ["", "Return valid JSON only, following the system prompt schema."]
    return "\n".join(lines)


def expected_d_question(
    template_id: str, span: dict[str, Any], d_templates: dict[str, str], meta: dict[str, Any]
) -> str | None:
    if template_id not in d_templates:
        return None
    frame_label = f"{span['start_frame']}-{span['end_frame']}"
    feedback_points = feedback_points_label(template_id, d_templates, meta["grs_subscores"])
    return render_d_question(template_id, d_templates, f"frames {frame_label}", feedback_points)


def video_frame_extent(spans: list[dict[str, Any]]) -> tuple[int, int]:
    return min(s["start_frame"] for s in spans), max(s["end_frame"] for s in spans)


def video_timestamp_label(spans: list[dict[str, Any]]) -> str:
    start_frame, end_frame = video_frame_extent(spans)
    return f"{frame_to_timestamp(start_frame)}-{frame_to_timestamp(end_frame)}"


def build_user_prompt_video(
    template_id: str,
    meta: dict[str, Any],
    spans: list[dict[str, Any]],
    d_templates: dict[str, str],
    procedure_or_task: str,
    recent_openers: list[str] | None = None,
) -> str:
    timestamp_label = video_timestamp_label(spans)
    feedback_points = feedback_points_label(template_id, d_templates, meta["grs_subscores"])
    lines = [
        "Dataset-specific input (ANNOTATION-ONLY: no frames or images are attached):",
        "- dataset_name: JIGSAWS",
        f"- procedure_or_task: {procedure_or_task}",
        f"- video_id: {meta['trial_id']}",
        f"- clip_id: {meta['trial_id']}",
        f"- timestamp_or_frame: {timestamp_label}",
        f"- requested_template_ids: {template_id}",
        "- number_of_questions: 1",
        "- available_annotations:",
        f"  - trial_id: {meta['trial_id']}",
        f"  - skill_level: {meta['skill_level']} ({SKILL_LEVELS.get(meta['skill_level'], 'unknown')})",
        f"  - grs_total: {meta['grs_total']}",
        f"  - grs_subscores: {json.dumps(meta['grs_subscores'], sort_keys=True)}",
    ]
    if feedback_points is not None:
        lines.append(f"  - three_feedback_points: {feedback_points}")
    lines += [
        "",
        "Ground the QA pair only in these annotations. Do not describe any visual",
        "content; no visual content was provided.",
    ]
    if template_id in d_templates:
        lines += recent_openers_block(recent_openers)
        question = render_d_question(template_id, d_templates, timestamp_label, feedback_points)
        lines += ["", "Use this exact question text:", question]
    lines += ["", "Return valid JSON only, following the system prompt schema."]
    return "\n".join(lines)


def expected_d_question_video(
    template_id: str, spans: list[dict[str, Any]], d_templates: dict[str, str], meta: dict[str, Any]
) -> str | None:
    if template_id not in d_templates:
        return None
    timestamp_label = video_timestamp_label(spans)
    feedback_points = feedback_points_label(template_id, d_templates, meta["grs_subscores"])
    return render_d_question(template_id, d_templates, timestamp_label, feedback_points)


def parse_json_payload(text: str) -> Any:
    stripped = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL | re.IGNORECASE)
    stripped = re.sub(r"^.*?</think>", "", stripped, flags=re.DOTALL | re.IGNORECASE)
    stripped = re.sub(r"<\|[^>]+?\|>", "", stripped).strip()
    fence_match = re.search(r"```(?:json)?\s*(.*?)```", stripped, flags=re.DOTALL | re.IGNORECASE)
    if fence_match:
        stripped = fence_match.group(1).strip()
    start_candidates = [index for index in (stripped.find("["), stripped.find("{")) if index >= 0]
    if not start_candidates:
        return json.loads(stripped)
    start = min(start_candidates)
    opener = stripped[start]
    closer = "]" if opener == "[" else "}"
    depth = 0
    in_string = False
    escaped = False
    for index in range(start, len(stripped)):
        char = stripped[index]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == opener:
            depth += 1
        elif char == closer:
            depth -= 1
            if depth == 0:
                return json.loads(stripped[start : index + 1])
    return json.loads(stripped[start:])


def normalize_qa_objects(payload: Any) -> list[dict[str, Any]] | None:
    items = payload if isinstance(payload, list) else [payload]
    normalized: list[dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            return None
        if set(item.keys()) != {"question", "answer", "rationale"}:
            return None
        normalized.append(item)
    return normalized or None


def verify_ollama_model(host: str, model_name: str) -> None:
    """Fail fast (before generating anything) if the local Ollama server or
    model isn't reachable, instead of surfacing an opaque error mid-run."""
    import urllib.error
    import urllib.request

    url = f"{host.rstrip('/')}/api/show"
    body = json.dumps({"model": model_name}).encode("utf-8")
    request = urllib.request.Request(
        url, data=body, headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            response.read()
    except urllib.error.URLError as exc:
        raise SystemExit(
            f"Could not reach Ollama at {host} for model {model_name!r}: {exc}\n"
            "Is `ollama serve` running, and has the model been pulled/created?"
        ) from exc
    log(f"verified ollama model {model_name!r} at {host}")


# Repair for UTF-8 bytes that were decoded as cp1252, which turns an em-dash
# (E2 80 94) into "â€”" and a right single quote (E2 80 99) into "â€™".
#
# Nothing in this script produces that: it writes every file with
# encoding="utf-8". The damage came from a batch driver concatenating the
# per-task outputs with PowerShell's Get-Content, which defaults to the system
# ANSI codepage in 5.1 -- the per-task files were clean and only the combined
# file was corrupt. The drivers now pass -Encoding UTF8, so this is kept only for
# repairing batches produced before that fix; see
# scripts/repair_mojibake_in_records.py. It is deliberately not applied to
# generation output, which was never affected.
#
# The transform is exactly invertible: re-encode as cp1252 to recover the
# original bytes, then decode them as utf-8. Applied only when the signature is
# present and only when the round trip is lossless, so clean text and genuinely
# accented text are left untouched.
MOJIBAKE_SIGNATURE = "â€"


def repair_mojibake(text: str) -> str:
    if not text or MOJIBAKE_SIGNATURE not in text:
        return text
    try:
        fixed = text.encode("cp1252").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text
    return fixed if MOJIBAKE_SIGNATURE not in fixed else text


def run_generation_ollama(
    host: str,
    model_name: str,
    system_prompt: str,
    user_prompt: str,
    max_new_tokens: int,
    num_ctx: int,
    temperature: float = 0.0,
) -> str:
    import urllib.request

    url = f"{host.rstrip('/')}/api/chat"
    payload = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "stream": False,
        # num_ctx must cover prompt + thinking + answer, or Ollama's default
        # (sized off free VRAM, often as low as 4096) truncates mid-thinking.
        "options": {"temperature": temperature, "num_predict": max_new_tokens, "num_ctx": num_ctx},
    }
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request, timeout=600) as response:
        result = json.loads(response.read())
    message = result["message"]
    thinking = message.get("thinking") or ""
    content = message.get("content") or ""
    # Ollama splits reasoning into its own "thinking" field instead of inline
    # <think> tags; reassemble so the existing <think>-stripping parser works.
    return f"<think>{thinking}</think>{content}" if thinking else content


def load_text_model(model_id: str, device_map: str) -> tuple[Any, Any]:
    import torch
    import transformers
    from transformers import AutoProcessor

    log(f"loading processor for {model_id}")
    processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
    kwargs: dict[str, Any] = {
        "device_map": device_map,
        "trust_remote_code": True,
        "dtype": torch.bfloat16 if torch.cuda.is_available() else "auto",
    }
    # Qwen3.6 is a multimodal architecture; try VL model classes before CausalLM
    # (same proven chain as the legacy runner). Text-only prompts work fine --
    # no image is ever constructed or passed anywhere in this script.
    class_names = [
        "AutoModelForImageTextToText",
        "AutoModelForVision2Seq",
        "AutoModelForMultimodalLM",
        "AutoModelForCausalLM",
    ]
    errors: list[str] = []
    for class_name in class_names:
        model_cls = getattr(transformers, class_name, None)
        if model_cls is None:
            continue
        try:
            log(f"loading model with {class_name}")
            model = model_cls.from_pretrained(model_id, **kwargs)
            model.eval()
            log(f"model loaded: {type(model)}")
            # This cluster does not isolate GPUs, so accelerate can quietly
            # place layers on CPU/disk when another job is holding VRAM. That
            # runs, then OOMs mid-generation hours later. Fail loudly instead.
            hf_map = getattr(model, "hf_device_map", None) or {}
            devices = sorted({str(v) for v in hf_map.values()})
            log(f"device map devices: {devices}")
            offloaded = [k for k, v in hf_map.items() if str(v) in {"cpu", "disk"}]
            if offloaded:
                raise RuntimeError(
                    f"{len(offloaded)} modules offloaded to CPU/disk (insufficient free "
                    f"GPU memory); refusing to run - first offloaded: {offloaded[:5]}"
                )
            return processor, model
        except Exception as exc:  # noqa: BLE001
            errors.append(f"{class_name}: {exc}")
    raise RuntimeError("Could not load model with any AutoModel class:\n" + "\n".join(errors))


def run_generation(
    processor: Any,
    model: Any,
    system_prompt: str,
    user_prompt: str,
    max_new_tokens: int,
    temperature: float = 0.0,
) -> str:
    import torch

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    text = processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=True,
    )
    inputs = processor(text=[text], padding=True, return_tensors="pt")
    device = "cuda" if torch.cuda.is_available() else "cpu"
    inputs = inputs.to(device)
    # temperature 0 (the default) is greedy/deterministic, matching prior
    # behavior exactly. Sampling (temperature > 0) trades reproducibility for
    # lexical variety across records -- worth it for building a dataset from
    # many records that share the same underlying scores, since greedy
    # decoding tends to converge on nearly identical phrasing for them.
    generation_kwargs: dict[str, Any] = {"max_new_tokens": max_new_tokens}
    if temperature > 0:
        generation_kwargs["do_sample"] = True
        generation_kwargs["temperature"] = temperature
    else:
        generation_kwargs["do_sample"] = False
    with torch.no_grad():
        generated_ids = model.generate(**inputs, **generation_kwargs)
    trimmed = generated_ids[0][inputs.input_ids.shape[1] :]
    return processor.batch_decode(
        [trimmed], skip_special_tokens=False, clean_up_tokenization_spaces=False
    )[0]


def mock_raw_output(
    template_id: str, span: dict[str, Any], d_templates: dict[str, str], meta: dict[str, Any]
) -> str:
    frame_label = f"{span['start_frame']}-{span['end_frame']}"
    question = expected_d_question(template_id, span, d_templates, meta) or (
        f"{MOCK_WATERMARK} placeholder question for {template_id} at frames {frame_label}"
    )
    return json.dumps(
        [
            {
                "question": question,
                "answer": f"{MOCK_WATERMARK} placeholder answer for {template_id}",
                "rationale": f"{MOCK_WATERMARK} placeholder rationale for {template_id}",
            }
        ]
    )


def mock_raw_output_video(
    template_id: str, spans: list[dict[str, Any]], d_templates: dict[str, str], meta: dict[str, Any]
) -> str:
    timestamp_label = video_timestamp_label(spans)
    question = expected_d_question_video(template_id, spans, d_templates, meta) or (
        f"{MOCK_WATERMARK} placeholder question for {template_id} at {timestamp_label}"
    )
    return json.dumps(
        [
            {
                "question": question,
                "answer": f"{MOCK_WATERMARK} placeholder answer for {template_id}",
                "rationale": f"{MOCK_WATERMARK} placeholder rationale for {template_id}",
            }
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-root", default=None,
                        help="Default: /mnt/sun/shared/datasets/surgical_skill/JIGSAWS/<task>")
    parser.add_argument("--system-prompt", required=True, help="Path to annotation-only system-prompt-A-D.md")
    parser.add_argument("--d-templates", default=None, help="Path to template-questions-A-D.md (default: alongside system prompt)")
    parser.add_argument("--model-id", default="Qwen/Qwen3.6-35B-A3B")
    parser.add_argument("--task", choices=sorted(TASK_LABELS), default="Suturing",
                        help="Which JIGSAWS task --dataset-root points at (selects the meta_file name and procedure_or_task label)")
    parser.add_argument("--trial-id", default="Suturing_B001")
    parser.add_argument("--trial-ids", default=None,
                        help="Comma-separated trial IDs to run in one invocation; overrides --trial-id if given")
    parser.add_argument("--gesture-id", default=None, help="Restrict to one gesture ID (default: all spans in the trial; ignored with --granularity video)")
    parser.add_argument("--max-spans", type=int, default=0,
                        help="Cap the number of gesture spans processed (0 = all). "
                             "Ignored with --granularity video, which emits one unit per trial.")
    parser.add_argument("--granularity", choices=["gesture", "video"], default="gesture",
                        help="gesture (default): one QA object per gesture span, timestamp_or_frame is a frame "
                             "range. video: one QA object per whole trial, timestamp_or_frame is a timestamp "
                             "range -- use this across many trials, since every gesture in a trial shares the "
                             "same GRS scores and per-gesture questions are near-duplicates of each other.")
    parser.add_argument("--templates", default="A3,C1,C2,C3,C6,C7,D1,D2,D3,D4,D5")
    parser.add_argument("--max-new-tokens", type=int, default=2048)
    parser.add_argument("--max-retries", type=int, default=2,
                        help="Re-request a record when the model returns malformed JSON, a "
                             "misspelled key, or the wrong question wording. These are transient "
                             "formatting glitches, not content problems. Only applies with "
                             "--backend real and --temperature > 0 (a retry at temperature 0 "
                             "reproduces the same output). Retry count is recorded per record.")
    parser.add_argument("--temperature", type=float, default=0.0,
                         help="0.0 (default) is greedy/deterministic. >0 enables sampling, trading "
                              "reproducibility for lexical variety across records that share the same "
                              "underlying scores -- recommended for real dataset-building runs.")
    parser.add_argument("--device-map", default="auto")
    parser.add_argument("--backend", choices=["real", "mock"], default="real",
                        help="mock builds watermarked placeholder records for pipeline smoke tests only")
    parser.add_argument("--inference-engine", choices=["transformers", "ollama"], default="transformers",
                        help="transformers: load --model-id directly (cluster). "
                             "ollama: call a local `ollama serve` for a quantized GGUF (consumer GPU).")
    parser.add_argument("--ollama-model", default="qwen3.6-35b-a3b",
                        help="Model name/tag as known to the local Ollama server (only used with --inference-engine ollama)")
    parser.add_argument("--ollama-host", default="http://localhost:11434")
    parser.add_argument("--ollama-num-ctx", type=int, default=8192,
                        help="Context window passed to Ollama; must fit prompt + thinking + answer or generation truncates")
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()

    requested = [item.strip() for item in args.templates.split(",") if item.strip()]
    unsupported = [item for item in requested if item in UNSUPPORTED_TEMPLATES]
    unknown = [item for item in requested if item not in SUPPORTED_TEMPLATES and item not in UNSUPPORTED_TEMPLATES]
    if unknown:
        parser.error(f"Unknown template IDs: {unknown}")
    if unsupported:
        reasons = {item: UNSUPPORTED_TEMPLATES[item] for item in unsupported}
        parser.error(
            "These templates cannot be generated annotation-only from JIGSAWS: "
            f"{json.dumps(reasons)}"
        )
    templates = [item for item in requested if item in SUPPORTED_TEMPLATES]

    dataset_root = Path(
        args.dataset_root
        or f"/mnt/sun/shared/datasets/surgical_skill/JIGSAWS/{args.task}"
    )
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    system_prompt_path = Path(args.system_prompt)
    system_prompt = extract_system_prompt(system_prompt_path)
    d_templates_path = (
        Path(args.d_templates)
        if args.d_templates
        else system_prompt_path.parent / "template-questions-A-D.md"
    )
    d_templates = load_d_templates(d_templates_path)

    trial_ids = (
        [item.strip() for item in args.trial_ids.split(",") if item.strip()]
        if args.trial_ids
        else [args.trial_id]
    )
    procedure_or_task = TASK_LABELS[args.task]
    task_slug = args.task.lower()

    processor = model = None
    if args.backend == "real":
        if args.inference_engine == "ollama":
            verify_ollama_model(args.ollama_host, args.ollama_model)
        else:
            processor, model = load_text_model(args.model_id, args.device_map)

    output_name = "qa_records.jsonl" if args.backend == "real" else "qa_records.mock.jsonl"
    output_path = output_dir / output_name
    valid = rejected = 0
    total_units = 0
    # Each record is one independent model call with no memory of what it
    # wrote for other records -- threading recent openers per template_id
    # into later prompts gives the model the cross-record awareness a shared
    # system prompt alone cannot provide.
    recent_openers_by_template: dict[str, list[str]] = {}
    with output_path.open("w", encoding="utf-8") as handle:
        for trial_id in trial_ids:
            meta = read_meta(dataset_root, trial_id, args.task)
            spans = read_gesture_spans(dataset_root, trial_id)
            if args.gesture_id:
                spans = [span for span in spans if span["gesture_id"] == args.gesture_id]
                if not spans:
                    raise SystemExit(f"Gesture {args.gesture_id} not found for {trial_id}")
            # Capping spans only makes sense per-gesture; in video mode the whole
            # trial is one unit and truncating spans would silently shorten the
            # timestamp range the question refers to.
            if args.max_spans > 0 and args.granularity == "gesture":
                spans = spans[: args.max_spans]

            units = [("video", spans)] if args.granularity == "video" else [
                ("gesture", [span]) for span in spans
            ]

            for unit_kind, unit_spans in units:
                for template_id in templates:
                    total_units += 1
                    recent_openers = recent_openers_by_template.get(template_id, [])[-RECENT_OPENERS_TO_SHOW:]
                    if unit_kind == "video":
                        user_prompt = build_user_prompt_video(
                            template_id, meta, unit_spans, d_templates, procedure_or_task, recent_openers
                        )
                        expected_question = expected_d_question_video(template_id, unit_spans, d_templates, meta)
                    else:
                        user_prompt = build_user_prompt(
                            template_id, meta, unit_spans[0], d_templates, procedure_or_task, recent_openers
                        )
                        expected_question = expected_d_question(template_id, unit_spans[0], d_templates, meta)

                    # The model intermittently emits a malformed envelope --
                    # observed misspelling the "rationale" key as "rationate",
                    # and occasionally truncating mid-JSON -- while the QA
                    # content itself is fine. These are transient formatting
                    # glitches, so ask again rather than discarding the record.
                    # Retrying only helps when sampling is on; at temperature 0
                    # a retry reproduces the same output byte for byte.
                    attempts = 0
                    earlier_errors: list[str] = []
                    while True:
                        attempts += 1
                        if args.backend == "mock":
                            raw_output = (
                                mock_raw_output_video(template_id, unit_spans, d_templates, meta)
                                if unit_kind == "video"
                                else mock_raw_output(template_id, unit_spans[0], d_templates, meta)
                            )
                        elif args.inference_engine == "ollama":
                            raw_output = run_generation_ollama(
                                args.ollama_host, args.ollama_model, system_prompt, user_prompt,
                                args.max_new_tokens, args.ollama_num_ctx, args.temperature,
                            )
                        else:
                            raw_output = run_generation(
                                processor, model, system_prompt, user_prompt, args.max_new_tokens, args.temperature
                            )
                        qa_objects = None
                        error = None
                        try:
                            qa_objects = normalize_qa_objects(parse_json_payload(raw_output))
                            if qa_objects is None:
                                error = "schema_mismatch: expected objects with exactly question/answer/rationale"
                        except Exception as exc:  # noqa: BLE001
                            error = repr(exc)

                        if error is None and expected_question is not None:
                            if qa_objects[0]["question"] != expected_question:
                                error = "question_mismatch: D question must match template wording exactly"

                        retryable = (
                            error is not None
                            and attempts <= args.max_retries
                            and args.backend == "real"
                            and args.temperature > 0
                        )
                        if not retryable:
                            break
                        earlier_errors.append(error)
                        log(f"  retry {attempts}/{args.max_retries} after: {error}")

                    if error is None:
                        status = "valid" if args.backend == "real" else "valid_mock"
                        valid += 1
                        if args.backend == "real" and template_id in d_templates:
                            recent_openers_by_template.setdefault(template_id, []).append(
                                first_sentence(qa_objects[0]["answer"])
                            )
                    else:
                        status = "rejected"
                        rejected += 1

                    if unit_kind == "video":
                        timestamp_label = video_timestamp_label(unit_spans)
                        start_frame, end_frame = video_frame_extent(unit_spans)
                        qa_id = f"jigsaws_{task_slug}_{template_id.lower()}_{meta['trial_id']}_video_anno"
                        source_annotation = {
                            "meta_file": meta["source_file"],
                            "transcription_file": unit_spans[0]["source_file"],
                            "skill_level": meta["skill_level"],
                            "grs_total": meta["grs_total"],
                            "grs_subscores": meta["grs_subscores"],
                            "video_timestamp_span": timestamp_label,
                            "video_frame_span": f"{start_frame}-{end_frame}",
                            "fps_used_for_timestamp_conversion": JIGSAWS_FPS,
                            "gesture_count": len(unit_spans),
                        }
                        timestamp_or_frame = timestamp_label
                    else:
                        span = unit_spans[0]
                        frame_label = f"{span['start_frame']}-{span['end_frame']}"
                        qa_id = (
                            f"jigsaws_{task_slug}_{template_id.lower()}_{meta['trial_id']}_"
                            f"{span['gesture_id']}_{frame_label.replace('-', '_')}_anno"
                        )
                        source_annotation = {
                            "meta_file": meta["source_file"],
                            "transcription_file": span["source_file"],
                            "skill_level": meta["skill_level"],
                            "grs_total": meta["grs_total"],
                            "grs_subscores": meta["grs_subscores"],
                            "gesture_id": span["gesture_id"],
                            "gesture_definition": GESTURE_DEFINITIONS.get(span["gesture_id"]),
                            "gesture_frame_range": frame_label,
                        }
                        timestamp_or_frame = frame_label

                    record = {
                        "qa_id": qa_id,
                        "dataset": "JIGSAWS",
                        "procedure_or_task": procedure_or_task,
                        "generation_mode": "annotation_only",
                        "template_id": template_id,
                        "template_support": SUPPORTED_TEMPLATES[template_id],
                        "trial_id": meta["trial_id"],
                        "timestamp_or_frame": timestamp_or_frame,
                        "source_annotation": source_annotation,
                        "model": {
                            "backend": args.backend,
                            "real_model_inference": args.backend == "real",
                            "inference_engine": args.inference_engine if args.backend == "real" else None,
                            "model_id": (
                                (args.ollama_model if args.inference_engine == "ollama" else args.model_id)
                                if args.backend == "real"
                                else None
                            ),
                            "system_prompt_path": str(system_prompt_path),
                            "attempts": attempts,
                            "retried_after_errors": earlier_errors or None,
                            "prompt": user_prompt,
                            "raw_output": raw_output,
                        },
                        "qa": qa_objects,
                        "validation_status": status,
                        "validation_error": error,
                    }
                    handle.write(json.dumps(record, ensure_ascii=False) + "\n")
                    log(f"{record['qa_id']}: {status}" + (f" ({error})" if error else ""))

    summary = {
        "backend": args.backend,
        "task": args.task,
        "granularity": args.granularity,
        "trial_ids": trial_ids,
        "templates": templates,
        "units": total_units,
        "valid": valid,
        "rejected": rejected,
        "output": str(output_path),
    }
    (output_dir / "run_summary.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
